### ISSUE TITLE
Add dashboard controller

### ISSUE THREAD

**Issue by jeremyFreeAgent** [rezzza/BitterBundle#13]
The dashboard will display stats about events as follow by default:
- this hour vs last hour
- today vs yesterday
- this week vs last week
- this month vs last month

And custom stats defined by the app developer like:
- when vs when
  *periods (like every day for X days)

**Comment by stephpy** [comment]
What about keys ? Users should have to define keys to show ?

What do you think about a configuration like that:

``` yml
rezzza_bitter:
   #....
   dashboard:
       template: ~ #...dashboard.twig
       comparators:
           default:
              - [from: yesterday, to: today]
              - [from: ..., to: ...]
       keys:
           chuck_norris:
               title: 'Chuck norris key'
               comparator: default # applicate array via normalization.
           song:
               title: 'Song key'
               comparator:
                  - [from: "-2 days", to: today]
                  - [from: ..., to: ...]
```
