### ISSUE TITLE
Profiler

### ISSUE THREAD

**Issue by stephpy** [rezzza/BitterBundle#14]
I guess we could add a profiler section on this bundle to aggregate stats from users requests.
Of course, it should be optional.
- 40x displayed
- 50x displayed
- Pages displayed
- nb logins
- counter by page (via routing)

**Comment by jeremyFreeAgent** [comment]
:+1:

**Comment by stephpy** [comment]
Configuration:

``` yml
rezzza_bitter:
    profiler: # if false (default), it'll be deactivated.
        consumers:
            status_code: [40x, 50x]
            login: ~
            page_showed: ~
            route_matched: [homepage, etc....]
```

btw, it could be possible to add consumers easily via a tag.
